services:
  postgres:
    container_name: crud_cursos_postgres
    image: postgres
    secrets:
      - db_password_secret
      - db_user_secret
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user_secret
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password_secret
      POSTGRES_DB: crud_cursos

secrets:
  db_user_secret:
    file: ./db_user_secret
  db_password_secret:
    file: ./db_password_secret
